backend:
  name: git-gateway
  branch: main
  repo: lorenareisx/sennacar

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "produtos"
    label: "Produtos"
    label_singular: "Produto"
    folder: "data/produtos"  # Pasta onde os produtos serão salvos
    create: true
    slug: "{{slug}}"
    identifier_field: "nome"
    format: json
    extension: json
    fields:
      - {label: "Nome", name: "nome", widget: "string", required: true}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "Preço", name: "preco", widget: "number", value_type: "float", step: 0.01}
      - {label: "Imagem", name: "imagem", widget: "image"}
      - {label: "Destaque", name: "destaque", widget: "boolean", default: false}