backend:
  name: git-gateway
  branch: main
  repo: lorenareisx/sennacar

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "data/produtos"  # Pasta onde os arquivos são salvos
    create: true
    slug: "{{slug}}"
    format: json
    identifier_field: "nome"
    fields:
      - {label: "Nome", name: "nome", widget: "string", required: true}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "Preço", name: "preco", widget: "number", value_type: "float"}
      - {label: "Imagem", name: "imagem", widget: "image"}
      - {label: "Destaque", name: "destaque", widget: "boolean"}