backend:
  name: git-gateway
  branch: main
  repo: lorenareisx/sennacar
  commit_messages:
    create: "Criado {{collection}} '{{slug}}'"
    update: "Atualizado {{collection}} '{{slug}}'"
    delete: "Removido {{collection}} '{{slug}}'"
    uploadMedia: "Upload de mídia '{{path}}'"
    deleteMedia: "Removido mídia '{{path}}'"

publish_mode: editorial_workflow
media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "produtos"
    label: "Produtos"
    label_singular: "Produto"  # Adicione esta linha
    file: "data/produtos.json"
    create: true
    format: json
    slug: "{{slug}}"  # Adicione esta linha
    identifier_field: "nome"  # Adicione esta linha
    fields:
      - {label: "Nome", name: "nome", widget: "string", required: true}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "Preço", name: "preco", widget: "number", value_type: "float"}
      - {label: "Imagem", name: "imagem", widget: "image", required: false}
      - {label: "Destaque", name: "destaque", widget: "boolean", required: false}