backend:
  name: git-gateway
  branch: main # ou o branch que você usa

media_folder: "img/uploads" # pasta onde as imagens serão armazenadas
public_folder: "/img/uploads"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "data/produtos"  # Pasta onde os produtos serão salvos
    create: true
    slug: "{{slug}}"
    format: json  # Garante que será salvo como JSON
    fields:
      - {label: "Nome", name: "nome", widget: "string"}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "Preço", name: "preco", widget: "number", valueType: "float"}
      - {label: "Imagem", name: "imagem", widget: "image", required: false}
      - {label: "Destaque", name: "destaque", widget: "boolean", required: false}