backend:
  name: git-gateway
  branch: main
  repo: lorenareisx/sennacar

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "produtos"  # ÚNICA coleção
    label: "Produtos"
    label_singular: "Produto"
    file: "data/produtos.json"  # ARQUIVO ÚNICO
    format: json
    fields:
      - name: "produtos"
        label: "Lista de Produtos"
        widget: "list"
        fields:
          - {label: "Nome", name: "nome", widget: "string", required: true}
          - {label: "Descrição", name: "descricao", widget: "text"}
          - {label: "Preço", name: "preco", widget: "number", value_type: "float"}
          - {label: "Imagem", name: "imagem", widget: "image"}
          - {label: "Destaque", name: "destaque", widget: "boolean", default: false}