backend:
  name: git-gateway
  branch: main
  repo: lorenareisx/sennacar
  commit_messages:
    create: "Criado {{collection}} '{{slug}}'"
    update: "Atualizado {{collection}} '{{slug}}'"
    delete: "Removido {{collection}} '{{slug}}'"
    uploadMedia: "Upload de mídia '{{path}}'"
    deleteMedia: "Removido mídia '{{path}}'"

# Configurações gerais
publish_mode: editorial_workflow
media_folder: "img/uploads"
public_folder: "/img/uploads"

# Coleções
collections:
  - name: "produtos"
    label: "Produtos"
    label_singular: "Produto"
    description: "Lista de produtos disponíveis"
    folder: "data/produtos"  # Mudado de 'file' para 'folder'
    create: true
    slug: "{{slug}}"
    identifier_field: "nome"
    format: "json"
    extension: "json"
    fields:
      - {label: "Nome", name: "nome", widget: "string", required: true}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "Preço", name: "preco", widget: "number", value_type: "float", step: 0.01}
      - {label: "Imagem", name: "imagem", widget: "image", required: false}
      - {label: "Destaque", name: "destaque", widget: "boolean", required: false, default: false}

        - name: "produtos_lista"
    label: "Lista de Produtos"
    file: "data/produtos/produtos.json"
    fields:
      - {
          name: "produtos",
          label: "Produtos",
          widget: "list",
          fields: [
            {label: "Nome", name: "nome", widget: "string"},
            {label: "Descrição", name: "descricao", widget: "text"},
            {label: "Preço", name: "preco", widget: "number"},
            {label: "Imagem", name: "imagem", widget: "image"},
            {label: "Destaque", name: "destaque", widget: "boolean"}
          ]
        }